119 3 1																																																																																																																						
# N D T																																																																																																																						
N	D	N	N	N	D	D	T	T	N	D	N	N	N	D	D	T	N	D	N	N	N	D	D	T	N	D	N	N	N	D	T	T	D	D	T	N	T	D	T	N	D	N	N	T	T	T	N	D	D	T	N	T	T	T	N	D	D	T	N	T	T	T	N	D	D	T	N	T	T	T	N	D	T	N	T	T	T	N	D	D	T	N	T	T	D	N	D	D	T	N	T	T	D	N	D	D	N	N	T	T	D	D	D	D	N	N	T	T	D	D	N	D	N	N	T	T	T	T
